"""Task
The provided code stub reads two integers from STDIN, A and B. Add code to print three lines where:

The first line contains the sum of the two numbers.
The second line contains the difference of the two numbers (first - second).
The third line contains the product of the two numbers.
Example


Print the following:

8
-2
15"""


a=int(input("Enter the first number"))
b=int(input("Enter the second number"))

sum=a+b
diff=a-b
prod=a*b

print("sum of two number is",sum)
print("diff is",diff)
print("prod is",prod)

#Hacckerrank accepted code
    # a= int(input())
    # b = int(input())


    # print(a+b)
    # print(a-b)
    # print(a*b)